### ISSUE TITLE
return full log from 'broadcastTransaction' method

### ISSUE THREAD

**Issue by andrzejchm** [Zfinix/tendermint_starport#2]
by default, `broadcastTransaction` method returns `TransactionHash` if the transaction is successfully broadcasted to the chain, but it would be also beneficial to get the full transaction object that consists of the full logs and any potential errors that would explain why transaction has failed.

**Comment by Zfinix** [comment]
Oh no my transactions on the liquidity module never even got to the chain

**Comment by andrzejchm** [comment]
sorry, this issue was meant for the tendermint's flutter repository

**Comment by Zfinix** [comment]
> sorry, this issue was meant for the tendermint's flutter repository

Oh okay i can comment there right?
